 
# SPDX-FileCopyrightText: 2021 Lisa Biermann
# SPDX-License-Identifier: GPL-3.0-or-later

name: ctest mac CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"

    steps:
    - uses: actions/checkout@v2
      with:
          persist-credentials: false
    - name : installPackages
      run : brew install eigen
    - name: cmake
      run: mkdir build && cd build && cmake .. 
    - name: make
      run: cd build && cmake --build . -j
    - name: Test
      run: cd build && ctest --output-on-failure